### ISSUE TITLE
Error while following Shaka Tutorial (method render cannot be accessed)

### ISSUE THREAD

**Issue by oliver-brm** [getshaka-org/shaka-docsite#1]
Following the tutorial, I ran into the error: 

    method render cannot be accessed as a member of org.getshaka.shaka.Frag.type from class Board.

in the `Board` class, see also [here](https://github.com/getshaka-org/shaka-docsite/blob/70de2988516d6e97a2fd64268ca644c9ec1b0288/src/main/scala/org/getshaka/shaka/docsite/Tutorial.scala#L250)

A reproducer is [here](https://github.com/oliver-brm/shaka-tutorial)

**Comment by oliver-brm** [comment]
Resolved in [version 0.4.1](https://github.com/getshaka-org/shaka/releases/tag/v0.4.1)

**Comment by AugustNagro** [comment]
Thanks for your issue. I pushed a fix here:

https://github.com/getshaka-org/shaka/pull/5

And published v0.4.1 to maven.

Also, I've updated the `shaka-docsite` repo; I had forgotten to push since I published v0.4.0.
